# Generated by Django 5.2.7 on 2025-11-20 02:32

import django.db.models.deletion
from django.db import migrations, models


def seed_existing_objects(apps, schema_editor):
    SessionQuestion = apps.get_model("quiz_sessions", "SessionQuestion")
    SessionParticipant = apps.get_model("quiz_sessions", "SessionParticipant")
    QuestionStat = apps.get_model("quiz_analytics", "QuestionStat")
    ScoreSummary = apps.get_model("quiz_analytics", "ScoreSummary")
    for session_question in SessionQuestion.objects.all():
        QuestionStat.objects.get_or_create(session_question=session_question)
    for participant in SessionParticipant.objects.select_related("session"):
        ScoreSummary.objects.get_or_create(
            participant=participant,
            defaults={"session": participant.session},
        )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quiz_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_responses", models.PositiveIntegerField(default=0)),
                ("correct_responses", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("distribution", models.JSONField(blank=True, default=dict)),
                (
                    "session_question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat",
                        to="quiz_sessions.sessionquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["session_question__order"],
            },
        ),
        migrations.CreateModel(
            name="ScoreSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_questions", models.PositiveIntegerField(default=0)),
                ("answered_questions", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                (
                    "participant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_summary",
                        to="quiz_sessions.sessionparticipant",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_summaries",
                        to="quiz_sessions.quizsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-accuracy", "participant__created_at"],
            },
        ),
        migrations.RunPython(seed_existing_objects, migrations.RunPython.noop),
    ]
