# Generated by Django 5.2.7 on 2026-01-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_options_customuser_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
