# Generated by Django 5.2.7 on 2026-01-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="enrollment_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="major",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nim",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
