# Generated by Django 5.2.7 on 2026-01-27 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_code",
                    models.CharField(help_text="Kode mata kuliah", max_length=50),
                ),
                (
                    "course_name",
                    models.CharField(help_text="Nama mata kuliah", max_length=200),
                ),
                (
                    "class_name",
                    models.CharField(
                        help_text="Nama kelas (e.g., IF-A)", max_length=50
                    ),
                ),
                (
                    "lecturer_id",
                    models.CharField(help_text="ID dosen dari SIS", max_length=50),
                ),
                (
                    "lecturer_name",
                    models.CharField(help_text="Nama dosen", max_length=200),
                ),
                ("date", models.DateField(help_text="Tanggal perkuliahan")),
                ("day_name", models.CharField(help_text="Nama hari", max_length=20)),
                (
                    "start_time",
                    models.TimeField(blank=True, help_text="Jam mulai", null=True),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, help_text="Jam selesai", null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "ordering": ["-date", "-created_at"],
                "unique_together": {
                    ("course_code", "class_name", "date", "lecturer_id")
                },
            },
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id",
                    models.CharField(help_text="NIM mahasiswa", max_length=50),
                ),
                (
                    "student_name",
                    models.CharField(help_text="Nama mahasiswa", max_length=200),
                ),
                (
                    "student_photo_url",
                    models.URLField(
                        blank=True, default="", help_text="URL foto mahasiswa"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hadir", "Hadir"),
                            ("sakit", "Sakit"),
                            ("dispensasi", "Dispensasi"),
                            ("alpha", "Alpha"),
                        ],
                        default="alpha",
                        max_length=20,
                    ),
                ),
                (
                    "face_recognized",
                    models.BooleanField(
                        default=False, help_text="Apakah wajah dikenali oleh sistem"
                    ),
                ),
                (
                    "recognized_at",
                    models.DateTimeField(
                        blank=True, help_text="Waktu wajah dikenali", null=True
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Skor confidence face recognition",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Catatan tambahan"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["student_name"],
                "unique_together": {("session", "student_id")},
            },
        ),
    ]
