# Generated by Django 5.2.7 on 2026-01-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="course_id",
            field=models.CharField(
                default="",
                help_text="ID mata kuliah dari SIS (IdCourse)",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="attendancesession",
            name="course_code",
            field=models.CharField(
                help_text="Kode mata kuliah (KodeMk)", max_length=50
            ),
        ),
    ]
