# Generated by Django 5.2.7 on 2026-01-28 02:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0002_attendancesession_course_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together=set(),
        ),
    ]
