# Generated by Django 5.2.7 on 2026-01-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0003_remove_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("hadir", "Hadir"),
                    ("sakit", "Sakit"),
                    ("izin", "Izin"),
                    ("dispensasi", "Dispensasi"),
                    ("alpha", "Alpha"),
                ],
                default="alpha",
                max_length=20,
            ),
        ),
    ]
