# Generated by Django 5.2.7 on 2026-01-28 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_alter_attendancerecord_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SisCourse",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="IdCourse dari SIS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Kode mata kuliah (KodeMk)", max_length=50
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nama mata kuliah", max_length=200),
                ),
                (
                    "credits",
                    models.PositiveSmallIntegerField(default=0, help_text="SKS"),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Program studi",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SIS Course",
                "verbose_name_plural": "SIS Courses",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="SisLecturer",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="StaffId dari SIS",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "id_staff",
                    models.IntegerField(
                        blank=True, help_text="IdStaff (numeric) dari SIS", null=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nama lengkap dosen (StaffName)", max_length=200
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path foto dosen",
                        max_length=500,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SIS Lecturer",
                "verbose_name_plural": "SIS Lecturers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SisStudent",
            fields=[
                (
                    "nim",
                    models.CharField(
                        help_text="NIM mahasiswa",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Nama mahasiswa",
                        max_length=200,
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Path foto mahasiswa",
                        max_length=500,
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Program studi",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SIS Student",
                "verbose_name_plural": "SIS Students",
                "ordering": ["nim"],
            },
        ),
        migrations.CreateModel(
            name="SisCourseClass",
            fields=[
                (
                    "id",
                    models.CharField(
                        help_text="Composite ID: IdCourse_KodeKelas",
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "class_code",
                    models.CharField(help_text="Kode kelas (KodeKelas)", max_length=20),
                ),
                (
                    "room",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ruangan (KodeRuang)",
                        max_length=50,
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        blank=True, default="", help_text="Hari kuliah", max_length=20
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, help_text="Jam mulai", null=True),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, help_text="Jam selesai", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="attendance.siscourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "SIS Course Class",
                "verbose_name_plural": "SIS Course Classes",
                "ordering": ["course__code", "class_code"],
            },
        ),
        migrations.CreateModel(
            name="SisCourseClassLecturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecturers",
                        to="attendance.siscourseclass",
                    ),
                ),
                (
                    "lecturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_classes",
                        to="attendance.sislecturer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Class Lecturer",
                "verbose_name_plural": "Course Class Lecturers",
                "unique_together": {("course_class", "lecturer")},
            },
        ),
        migrations.CreateModel(
            name="SisEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="attendance.siscourseclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="attendance.sisstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "SIS Enrollment",
                "verbose_name_plural": "SIS Enrollments",
                "unique_together": {("course_class", "student")},
            },
        ),
    ]
