# Generated by ChatGPT on 2026-02-10

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0005_siscourse_sislecturer_sisstudent_siscourseclass_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BiometricRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                (
                    "student_nim",
                    models.CharField(help_text="NIM mahasiswa", max_length=50),
                ),
                (
                    "student_name",
                    models.CharField(blank=True, default="", help_text="Nama mahasiswa", max_length=200),
                ),
                (
                    "lecturer_id",
                    models.CharField(blank=True, default="", help_text="ID dosen (opsional)", max_length=50),
                ),
                (
                    "lecturer_name",
                    models.CharField(blank=True, default="", help_text="Nama dosen (opsional)", max_length=200),
                ),
                (
                    "face_front",
                    models.TextField(blank=True, default="", help_text="Base64 foto wajah depan"),
                ),
                (
                    "face_left",
                    models.TextField(blank=True, default="", help_text="Base64 foto wajah kiri"),
                ),
                (
                    "face_right",
                    models.TextField(blank=True, default="", help_text="Base64 foto wajah kanan"),
                ),
                (
                    "face_up",
                    models.TextField(blank=True, default="", help_text="Base64 foto wajah atas"),
                ),
                (
                    "face_front_mime",
                    models.CharField(blank=True, default="image/jpeg", max_length=50),
                ),
                (
                    "face_left_mime",
                    models.CharField(blank=True, default="image/jpeg", max_length=50),
                ),
                (
                    "face_right_mime",
                    models.CharField(blank=True, default="image/jpeg", max_length=50),
                ),
                (
                    "face_up_mime",
                    models.CharField(blank=True, default="image/jpeg", max_length=50),
                ),
                (
                    "voice_prompt_1_text",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "voice_prompt_2_text",
                    models.TextField(blank=True, default=""),
                ),
                (
                    "voice_recording_1",
                    models.TextField(blank=True, default="", help_text="Base64 audio rekaman 1"),
                ),
                (
                    "voice_recording_2",
                    models.TextField(blank=True, default="", help_text="Base64 audio rekaman 2"),
                ),
                (
                    "voice_recording_1_mime",
                    models.CharField(blank=True, default="audio/webm", max_length=50),
                ),
                (
                    "voice_recording_2_mime",
                    models.CharField(blank=True, default="audio/webm", max_length=50),
                ),
                (
                    "voice_recording_1_duration",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "voice_recording_2_duration",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "is_complete",
                    models.BooleanField(default=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biometric_registrations",
                        to="attendance.sisstudent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Biometric Registration",
                "verbose_name_plural": "Biometric Registrations",
                "ordering": ["-created_at"],
            },
        ),
    ]
