# Generated by ChatGPT on 2026-01-28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_biometric_registration"),
    ]

    operations = []
