# Generated by GitHub Copilot on 2026-01-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_email_facesample_faceenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="facesample",
            name="enrollment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="accounts.faceenrollment",
            ),
        ),
        migrations.AddField(
            model_name="facesample",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("eyes_closed", "Eyes closed"),
                    ("mouth_open", "Mouth open"),
                ],
                default="neutral",
                max_length=20,
            ),
        ),
    ]
