# Generated by Django 5.2.7 on 2026-01-09 06:26

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_facesample_prompt_enrollment"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoiceEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(default="ecapa-tdnn", max_length=100)),
                (
                    "model_version",
                    models.CharField(
                        default="speechbrain/spkrec-ecapa-voxceleb", max_length=200
                    ),
                ),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VoiceSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio",
                    models.FileField(
                        upload_to=apps.accounts.models._voice_sample_upload_to
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("voice_active_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("voice_ratio", models.FloatField(blank=True, null=True)),
                ("vad_threshold", models.FloatField(blank=True, null=True)),
                ("rms_in", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="accounts.voiceenrollment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="voiceenrollment",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_vo_user_id_690096_idx"
            ),
        ),
    ]
