# Generated by Django 5.2.7 on 2026-01-20 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_fields_and_activity_log"),
        ("accounts", "0005_attendancesession_facelabelmapping_attendancerecord"),
    ]

    operations = []
